# Generated by Django 2.2.11 on 2020-04-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorldPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(
                    auto_created=True, 
                    on_delete=django.db.models.deletion.CASCADE, 
                    parent_link=True, 
                    primary_key=True, 
                    related_name='djangocms_hello_world_helloworldplugin', 
                    serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(
                    blank=True, 
                    null=True, 
                    verbose_name='Your custom text')),
            ],
            options={
                'verbose_name': 'Hello world plugin',
                'verbose_name_plural': 'Hello world plugins',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
